all: release debug

#/Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/Makefile.FL.Release: /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/FL.pro
#	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor && python /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/BuildSystem/BuildTools/Scripts/createProject.py FL
#/Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/Makefile.FL.Debug: /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/FL.pro
#	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor && python /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/BuildSystem/BuildTools/Scripts/createProject.py FL

release: #/Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/Makefile.FL.Release
	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor
	$(MAKE) -k -j 4 -f Makefile.FL.Release
debug: #/Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor/Makefile.FL.Debug 
	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor 
	$(MAKE) -k -j 4 -f Makefile.FL.Debug
cleanall: clean
cleanrelease:
	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor && if test -e Makefile.FL.Release; then $(MAKE) -k -f Makefile.FL.Release clean; fi
cleandebug:
	cd /Users/ilab/BuildSlaveWorkingDirectory/WD/MeVis/ThirdParty/Sources/Inventor/inventor && if test -e Makefile.FL.Debug; then $(MAKE) -k -f Makefile.FL.Debug clean; fi

clean: cleanrelease cleandebug

rebuilddebug: cleandebug debug

rebuildrelease: cleanrelease release
